# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Analyzer.ui'
#
# Created: Thu Apr 17 22:48:00 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(639, 624)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(360, 10, 161, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 111, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(10, 181, 211, 24))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 211, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(10, 225, 221, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(10, 263, 211, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.BrowseButton = QtGui.QPushButton(self.centralWidget)
        self.BrowseButton.setGeometry(QtCore.QRect(228, 27, 99, 27))
        self.BrowseButton.setObjectName(_fromUtf8("BrowseButton"))
        self.signalEnhancementMethod = QtGui.QComboBox(self.centralWidget)
        self.signalEnhancementMethod.setGeometry(QtCore.QRect(220, 180, 151, 27))
        self.signalEnhancementMethod.setObjectName(_fromUtf8("signalEnhancementMethod"))
        self.FeatureEnhancementMethod = QtGui.QComboBox(self.centralWidget)
        self.FeatureEnhancementMethod.setGeometry(QtCore.QRect(220, 220, 151, 27))
        self.FeatureEnhancementMethod.setObjectName(_fromUtf8("FeatureEnhancementMethod"))
        self.ClassifierBox = QtGui.QComboBox(self.centralWidget)
        self.ClassifierBox.setGeometry(QtCore.QRect(220, 260, 151, 27))
        self.ClassifierBox.setObjectName(_fromUtf8("ClassifierBox"))
        self.removeNoiseChecked = QtGui.QRadioButton(self.centralWidget)
        self.removeNoiseChecked.setGeometry(QtCore.QRect(120, 130, 117, 22))
        self.removeNoiseChecked.setObjectName(_fromUtf8("removeNoiseChecked"))
        self.removeNoiseUnchecked = QtGui.QRadioButton(self.centralWidget)
        self.removeNoiseUnchecked.setGeometry(QtCore.QRect(260, 130, 117, 22))
        self.removeNoiseUnchecked.setObjectName(_fromUtf8("removeNoiseUnchecked"))
        self.StartSample = QtGui.QSlider(self.centralWidget)
        self.StartSample.setGeometry(QtCore.QRect(50, 100, 371, 29))
        self.StartSample.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.StartSample.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.StartSample.setAutoFillBackground(False)
        self.StartSample.setMinimum(3)
        self.StartSample.setMaximum(6)
        self.StartSample.setProperty("value", 3)
        self.StartSample.setOrientation(QtCore.Qt.Horizontal)
        self.StartSample.setInvertedAppearance(False)
        self.StartSample.setInvertedControls(False)
        self.StartSample.setTickPosition(QtGui.QSlider.NoTicks)
        self.StartSample.setTickInterval(1)
        self.StartSample.setObjectName(_fromUtf8("StartSample"))
        self.endSample = QtGui.QSlider(self.centralWidget)
        self.endSample.setGeometry(QtCore.QRect(170, 100, 360, 29))
        self.endSample.setMinimum(4)
        self.endSample.setMaximum(7)
        self.endSample.setProperty("value", 7)
        self.endSample.setTracking(False)
        self.endSample.setOrientation(QtCore.Qt.Horizontal)
        self.endSample.setInvertedAppearance(False)
        self.endSample.setInvertedControls(False)
        self.endSample.setTickPosition(QtGui.QSlider.NoTicks)
        self.endSample.setTickInterval(1)
        self.endSample.setObjectName(_fromUtf8("endSample"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(50, 80, 67, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(400, 80, 67, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(290, 80, 67, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(170, 80, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(520, 80, 67, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.datafile = QtGui.QTextEdit(self.centralWidget)
        self.datafile.setGeometry(QtCore.QRect(20, 30, 201, 21))
        self.datafile.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.datafile.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.datafile.setObjectName(_fromUtf8("datafile"))
        self.TrainButton = QtGui.QPushButton(self.centralWidget)
        self.TrainButton.setGeometry(QtCore.QRect(270, 300, 99, 27))
        self.TrainButton.setObjectName(_fromUtf8("TrainButton"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 639, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Select Data FIle ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Subject Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Sample Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Signal Enhancement Method: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "remove noise :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Feature enhancement method: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Classifier:", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseButton.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.removeNoiseChecked.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.removeNoiseUnchecked.setText(QtGui.QApplication.translate("MainWindow", "RadioButton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.TrainButton.setText(QtGui.QApplication.translate("MainWindow", "Train", None, QtGui.QApplication.UnicodeUTF8))

